### ISSUE TITLE
how to use this package with laravel, can show example please

### ISSUE THREAD

**Issue by kudaibergenoff** [matthewbdaly/laravel-gridfs-storage#1]
how to use this package with laravel, can show example please

**Comment by matthewbdaly** [comment]
It's not usable with current versions of PHP anyway due to an issue with Flysystem, and is effectively abandoned.

**Comment by matthewbdaly** [comment]
Please note that this package is essentially just a service provider for Laravel that allows the storage to use the Flysystem GridFS adapter. Since that adapter appears to have been removed from Flysystem, it's not really usable anymore.
